### 블로그 글 작성하기
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title": "제목 0",
  "content": "내용 0"
}

### 블로그 글 목록 가져오기
GET http://localhost:8080/api/articles

### 블로그 글 id로 가져오기
GET http://localhost:8080/api/articles/2

### 블로그 글 id로 삭제하기
DELETE http://localhost:8080/api/articles/2

### 블로그 글 업데이트하기
PUT http://localhost:8080/api/articles/1
Content-Type: application/json

{
  "title": "새 블로그",
  "content": "새로운 글을 써볼까?"
}